dorssel/usbipd-win

- .gitignore
- CODE_OF_CONDUCT.md
- GitVersion.yml
- Installer/HarvestTransform.xslt
- Installer/Installer.wixproj
- Installer/Product.wxs
- UsbIpServer/UsbIpServer.csproj
- UsbIpServer/app.manifest
- usbipd-win.sln
- include build number
- prevent multiple installs
> fix versioning and upgrades

- .editorconfig
- Installer/Installer.wixproj
- Installer/Product.wxs
- Installer/UserInterface.wxs
- README.md
- UsbIpServer/ConnectedClient.cs
- UsbIpServer/DeviceFile.cs
- UsbIpServer/Interop/VBoxUsb.cs
- UsbIpServer/Interop/WinSDK.cs
- UsbIpServer/Tools.cs
- UsbIpServer/UnexpectedResultException.cs
- UsbIpServer/UsbIpServer.csproj
- UsbIpServer/VBoxUsbMon.cs
Allows offline signing of the artifact.
Allows seamless upgrade.
> signed installer

- Installer/Installer.wixproj
- Installer/VSFixup.targets
> Fixed #6 - allow package restore from within VS

- Directory.Packages.props
- UsbIpServer/AttachedClient.cs
- UsbIpServer/ExportedDevice.cs
- UsbIpServer/Interop/Linux.cs
- UsbIpServer/Interop/Usb.cs
- UsbIpServer/Interop/VBoxUsb.cs
- UsbIpServer/Interop/WinSDK.cs
- UsbIpServer/Tools.cs
- add error conversion (VBox -> Linux)
- add STALL recovery
- add USB 3 support
- add alternate interface support
- fix reported device speed
> improve device support

- UsbIpServer/AttachedClient.cs
- UsbIpServer/ConnectedClient.cs
- UsbIpServer/LogEvents.cs
- UsbIpServer/Program.cs
- sane defaults
- enable EventLog for service
- configurable via environment & command line
> Add proper logging

- Installer/Product.wxs
- Installer/Server.wxs
- README.md
- UsbIpServer/Program.cs
- UsbIpServer/RegistryUtils.cs
- rename CLI tool to 'usbipd.exe'
- add installation directory to PATH
- add user friendly DisplayName and Description
- create/delete registry key via installer
> polish OOBE

- WSL_USBIP.md
I walked through the kernel instructions and have made some clean ups for clarification and added additional flags to support Arduino.
> Update kernel instructions

- .editorconfig
- WSL_USBIP.md
- also update .editorconfig to enforce white space convention
> fix markdownlint errors

- GitVersion.yml
- UsbIpServer/NativeMethods.txt
- UsbIpServer/Tools.cs
- UsbIpServer/VBoxUsbMon.cs
- also remove GetVersion override
> Add friendly name for device manager

- README.md
- UsbIpServer/AttachedClient.cs
- UsbIpServer/ConnectedClient.cs
- UsbIpServer/Interop/UsbIp.cs
- UsbIpServer/Program.cs
- UsbIpServer/Tools.cs
- WSL_USBIP.md
> Refactor endianness marshalling

- UsbIpServer/AttachedClient.cs
- UsbIpServer/BusId.cs
- UsbIpServer/ConnectedClient.cs
- UsbIpServer/DeviceChangeWatcher.cs
- UsbIpServer/DeviceChecker.cs
- UsbIpServer/ExportedDevice.cs
- UsbIpServer/ProcessUtils.cs
- UsbIpServer/RegistryUtils.cs
- UsbIpServer/RegistryWatcher.cs
- UsbIpServer/Tools.cs
- UsbIpServer/UsbConfigurationDescriptors.cs
- UsbIpServer/WslDistributions.cs
- Use target-typed new()
- Fix cSpell warnings
> Fix style and spelling

- UsbIpServer/WslDistributions.cs
> Support for WSL from Microsoft Store

- UsbIpServer/ConnectedClient.cs
- do not assume NUL padding
Fixes #79
> Fix parsing of attach BusId

- UsbIpServer/WslDistributions.cs
- no longer rely on 'hostname', which is distribution dependent
Fixes #85
> Improve WSL instance address detection

- .github/workflows/build.yml
- Directory.Packages.props
- Installer/Installer.wixproj
- InstallerDependencies/InstallerDependencies.csproj
- UsbIpServer/AttachedClient.cs
- UsbIpServer/ConnectedClient.cs
- UsbIpServer/LogEvents.cs
- UsbIpServer/Properties/PublishProfiles/InputForInstaller.pubxml
- UsbIpServer/Server.cs
- UsbIpServer/Tools.cs
- UsbIpServer/UsbIpServer.csproj
- global.json
- usbipd-win.sln
Best reviewed per individual commit
> Update to .NET 6 and Visual Studio 2022

- .github/workflows/build.yml
- Directory.Packages.props
- Installer/Installer.wixproj
- InstallerDependencies/InstallerDependencies.csproj
- UsbIpServer/AttachedClient.cs
- UsbIpServer/ConnectedClient.cs
- UsbIpServer/DeviceChangeWatcher.cs
- UsbIpServer/DeviceChecker.cs
- UsbIpServer/LogEvents.cs
- UsbIpServer/Properties/PublishProfiles/InputForInstaller.pubxml
- UsbIpServer/RegistryUtils.cs
- UsbIpServer/RegistryWatcher.cs
- UsbIpServer/Server.cs
- UsbIpServer/Tools.cs
- UsbIpServer/UsbIpServer.csproj
- UsbIpServer/WslDistributions.cs
- global.json
- usbipd-win.sln
- Force 64-bit WMI
- Adds logging on failed RegistryWatcher
Fixes #80
> Force 64-bit WMI provider

- UsbIpServer/Program.cs
> Improve WSL checks

- UsbIpServer/ConfigurationManager.cs
- UsbIpServer/ConnectedClient.cs
- UsbIpServer/Interop/WinSDK.cs
- UsbIpServer/NativeMethods.txt
- UsbIpServer/VBoxUsbMon.cs
> Add disable/enable during attach

- UsbIpServer/BusId.cs
- refactor to readonly record struct
> Cleanup BusId

- Installer/Installer.wixproj
- InstallerDependencies/InstallerDependencies.csproj
- global.json
- also fix Windows 8.0 minimum
> Bump Microsoft.Build.NoTargets

- UsbIpServer/Program.cs
- UsbIpServer/WslDistributions.cs
> Improve WSL sanity checks

- Installer/Product.wxs
> Fix updates

- UsbIpServer/ConfigurationManager.cs
- UsbIpServer/ConnectedClient.cs
- UsbIpServer/NativeMethods.txt
- UsbIpServer/ProcessUtils.cs
- UsbIpServer/RegistryUtils.cs
- UsbIpServer/Server.cs
- Use restart instead of disable/enable
- Fix unplug detect
- Fix cleanup on startup for non-present devices
Fixes #152 
Fixed #155 
Resolves #91
> Refactor attach

- UsbIpServer/ExportedDevice.cs
> Allow sharing of devices that are disabled on the host

- .github/workflows/build.yml
- Directory.Packages.props
- Drivers/VBoxUSBMon/VBoxUSBMon.cat.license
- Installer/HarvestTransform.xslt
- Installer/Installer.wixproj
- README.md
- UnitTests/BusIdTests.cs
- UnitTests/ParseBindCommand.cs
- UnitTests/ParseLicenseCommand.cs
- UnitTests/ParseListCommand.cs
- UnitTests/ParseRootCommand.cs
- UnitTests/ParseServerCommand.cs
- UnitTests/ParseTest.cs
- UnitTests/ParseUnbindCommand.cs
- UnitTests/ParseWslAttachCommand.cs
- UnitTests/ParseWslCommand.cs
- UnitTests/ParseWslDetachCommand.cs
- UnitTests/ParseWslListCommand.cs
- UnitTests/ProgramTests.cs
- UnitTests/UnitTests.csproj
- UsbIpServer/CommandHandlers.cs
- UsbIpServer/ConnectedClient.cs
- UsbIpServer/ConsoleTools.cs
- UsbIpServer/ProcessUtils.cs
- UsbIpServer/Program.cs
- UsbIpServer/UsbIpServer.csproj
- UsbIpServer/WslDistributions.cs
- usbipd-win.sln
- Add unit tests for command line parsing
- Use console coloring for error messages
> Refactor to System.CommandLine

- UsbIpServer/CommandHandlers.cs
> Add warning for incompatible UpperFilters

- .editorconfig
- UsbIpServer/CommandHandlers.cs
- UsbIpServer/ExportedDevice.cs
- UsbIpServer/ProcessUtils.cs
- UsbIpServer/Program.cs
- codecov.yml
- usbipd-win.sln
- no longer requires sudo password
> WSL attach as root

- UnitTests/BusId_Tests.cs
- UnitTests/ConfigurationManagerException_Tests.cs
- UnitTests/Tools_Tests.cs
- UsbIpServer/CommandHandlers.cs
- UsbIpServer/ConfigurationManager.cs
- UsbIpServer/ExportedDevice.cs
- UsbIpServer/ProcessUtils.cs
- UsbIpServer/RegistryUtils.cs
- UsbIpServer/UsbDevice.cs
- UsbIpServer/WslDistributions.cs
- sealed where possible
- modern style records
> Fix coding style

- Installer/Server.wxs
- UsbIpServer/CommandHandlers.cs
- UsbIpServer/ConsoleTools.cs
- UsbIpServer/RegistryUtils.cs
- UsbIpServer/Server.cs
- UsbIpServer/VBoxUsbMon.cs
- UsbIpServer/WslDistributions.cs
- also improve error reporting
> Add service dependency on VBoxUsbMon

- UsbIpServer/CommandHandlers.cs
- UsbIpServer/ConsoleTools.cs
- UsbIpServer/Program.cs
> Fix alignment of device descriptions

- UsbIpServer/CommandHandlers.cs
- UsbIpServer/Program.cs
- use command line GUIDs without parentheses
> Add dotnet-suggest completions

- Installer/Installer.wixproj
- Installer/Server.wxs
> Make failed service start on install non-fatal

- UsbIpServer/CommandHandlers.cs
- filter out not-connected devices
> Fix wsl list

- UsbIpServer/CommandHandlers.cs
- broken since using .NET 6 LoggerMessage
Fixes #235
> Fix creation of event source

- UsbIpServer/CommandHandlers.cs
- but only if there is more than 1
Fixes #251
> Report default distro used

- UsbIpServer/CommandHandlers.cs
- UsbIpServer/NativeMethods.txt
- differentiate between elevation (UAC) and standard/admin users
Fixes #243
Fixes #244
> Improve access check

- UsbIpServer/ConfigurationManager.cs
- UsbIpServer/ConsoleTools.cs
- UsbIpServer/Interop/VBoxUsb.cs
- UsbIpServer/Interop/VBoxUsbMon.cs
- UsbIpServer/VBoxUsbMon.cs
> Add VBoxUsbMon installation check

- UnitTests/Tools_Tests.cs
- UsbIpServer/AttachedClient.cs
- UsbIpServer/Tools.cs
> Queue replies per raw endpoint

- UsbIpServer/NewDev.cs
> Add delay between driver changes

- UnitTests/Automation_Tests.cs
- UnitTests/BusId_Tests.cs
- UnitTests/ExportedDevice_Tests.cs
- UnitTests/Parse_bind_Tests.cs
- UnitTests/Parse_unbind_Tests.cs
- UnitTests/Parse_wsl_attach_Tests.cs
- UnitTests/Parse_wsl_detach_Tests.cs
- UnitTests/UsbDevice_Tests.cs
- UnitTests/VidPid_Tests.cs
- Usbipd.Automation/BusId.cs
- Usbipd.Automation/Device.cs
- Usbipd.Automation/VidPid.cs
- Usbipd/CommandHandlers.cs
- Usbipd/ConfigurationManager.cs
- Usbipd/ConnectedClient.cs
- Usbipd/ConsoleTools.cs
- Usbipd/ExportedDevice.cs
- Usbipd/LogEvents.cs
- Usbipd/Program.cs
- Usbipd/RegistryUtils.cs
- Usbipd/UsbDevice.cs
- Usbipd/VBoxUsb.cs
- Usbipd/VidPid.cs
> Add option --hardware-id

- Usbipd/ConfigurationManager.cs
> Fix handling synchronous Wait and AggregateException

- Usbipd/CommandHandlers.cs
- Usbipd/wsl-scripts/auto-attach.sh
- fixes base-10 parsing for numbers with leading zeros
- allow auto-attach on already attached devices
Fixes #368
> Fix auto-attach

- Usbipd/NewDev.cs
- Usbipd/RegistryUtils.cs
- use APPLICATIONFOLDER instead
See https://github.com/dorssel/usbipd-win/issues/370#issuecomment-1120201152
> Fix hardcoded path

- Usbipd/Usbipd.csproj
https://github.com/dotnet/linker/issues/2622 has been fixed.
> Remove workaround for dotnet linker issue

- InstallerDependencies/InstallerDependencies.csproj
- global.json
- nuget.config
- Required since .NET SDK 6.0.300
> Add packageSourceMapping

- UnitTests/UnitTests.csproj
- Usbipd/Usbipd.csproj
> Improve CsWin32 usage

- Usbipd/AttachedClient.cs
> Fix number_of_packets

- Usbipd/Server.cs
> Make TCP Keep-Alive configurable

- Usbipd/ConfigurationManager.cs
> Add support for devices without any description

- Directory.Packages.props
- Usbipd.PowerShell/GetUsbipdDevice.cs
- Usbipd.PowerShell/Installation.cs
- Usbipd.PowerShell/Usbipd.PowerShell.csproj
- Microsoft.Win32.Registry is obsolete
- refactored
> Remove Microsoft.Win32.Registry dependency

- LICENSES/GPL-3.0-only.txt
- Usbipd/ConnectedClient.cs
> Fix URLs (https)

- Usbipd/ConfigurationManager.cs
> Fix port reset timing

- Usbipd/AttachedClient.cs
- Usbipd/AttachedEndpoint.cs
- Usbipd/ClientContext.cs
- Usbipd/ConnectedClient.cs
- Usbipd/RequestReply.cs
> Fix unlink race condition

- UnitTests/Parse_detach_Tests.cs
- Usbipd/CommandHandlers.cs
- Usbipd/Program.cs
> Make detach command generic

- Usbipd/Wsl.cs
> Add support for WSL [automount] configuration

- UnitTests/BusId_Tests.cs
- Usbipd.Automation/BusId.cs
- Usbipd.PowerShell/Installation.cs
- Usbipd/CommandHandlers.cs
- Usbipd/ConfigurationManager.cs
- Usbipd/Program.cs
> Fix crash for incompatible hubs

- Directory.Build.props
> +semver: minor

- Usbipd/Wsl.cs
> Fix mount options

- UnitTests/Automation_Tests.cs
- Usbipd.Automation/BusId.cs
- Usbipd.Automation/Device.cs
- Usbipd.Automation/JsonConverterBusId.cs
- Usbipd.Automation/JsonConverterIPAddress.cs
Use automatic handling of null
> Refactor JSON converters

- Usbipd/CommandHandlersInstaller.cs
- Usbipd/ConfigurationManager.cs
- Usbipd/ConnectedClient.cs
- Usbipd/DeviceFile.cs
- Usbipd/NewDev.cs
- Usbipd/Server.cs
- Usbipd/Tools.cs
- only use unsafe when unavoidable
> Suppress DevSkim warning for unsafe

- Installer/Installer.wixproj
- Installer/Product.wxs
- Installer/UserInterface.wxs
- also fixes copyright in installer dialog
- also use neutral codepage for the MSI installer
> Add SWID Tag

- .github/workflows/winget.yml
* https://github.com/vedantmgoyal9/winget-releaser/issues/289
> Update winget-releaser to pinned fix

- Usbipd/Wsl.cs
> Support WSL kernel modules

- .github/linters/.markdown-link-check.json
- .github/linters/.markdown-link-check.json.license
- UnitTests/Parse_attach_Tests.cs
- Usbipd/CommandHandlersCli.cs
- Usbipd/ICommandHandlers.cs
- Usbipd/Program.cs
- Usbipd/Wsl.cs
- add option --host-ip
- add option --unplugged
> Improve WSL (auto)attach

- Directory.Build.targets
- issue was fixed in HeatWave 1.0.5
> Revert HeatWave workaround

- Directory.Build.props
- UnitTests/UnitTests.csproj
- Usbipd.PowerShell/Installation.cs
- Usbipd/Usbipd.csproj
See https://github.com/dependabot/dependabot-core/issues/12274
> Fix Dependabot

- Usbipd/Wsl.cs
> Add support for non-FHS distributions
