- UsbIpServer/ConnectedClient.cs
- UsbIpServer/DeviceChecker.cs
- UsbIpServer/LogEvents.cs
- UsbIpServer/Program.cs
- UsbIpServer/RegistryUtils.cs
- UsbIpServer/RegistryWatcher.cs
- UsbIpServer/Server.cs
Changes on this PR:
- The tool now allows user to persistently share their devices.
- Users can query the devices "present" and devices "persisted" with the list command. 
- Present devices can be shared or un-shared with their bus-id. Persisted devices can be forgotten by providing a GUID.
- Present devices include a status column which indicates if the device is "not-shared", "shared" or "attached".
- A fix to a bug which showed the name of devices as "VirtualBox USB" after being attached.
Low level changes are:
- Saving a key in the registry for every device shared. The key is a GUID. The values are filters that identify the device and VIP which is the IP address of the virtual machine to which is attached to. Additionally, every key contains a volatile subkey that indicates if the …
> Persistency for Shared Devices

- UsbIpServer/ConnectedClient.cs
- UsbIpServer/DeviceChangeWatcher.cs
- UsbIpServer/NativeWslApi.cs
- UsbIpServer/ProcessUtils.cs
- UsbIpServer/Program.cs
- UsbIpServer/RegistryUtils.cs
- UsbIpServer/Server.cs
- UsbIpServer/WslDistributions.cs
- WSL_USBIP.md
Documentation for the new commands is available in the `WSL_USBIP.md` document. These changes provide a single command that allows users to share devices with a WSL instance. It takes care of sharing the device in the server and attaching the device from Linux, and makes it so that users don't need to know their IP address on Windows or Linux.
I also fixed a bug with the `IsServerRunning` mutex.
@NelsonDaniel adding you in case you're interested, but I know this is your last day, so don't feel like you need to review this.
> Add WSL convenience commands

- UsbIpServer/NativeMethods.txt
- UsbIpServer/Program.cs
- UsbIpServer/RegistryUtils.cs
- UsbIpServer/WslDistributions.cs
- WSL_USBIP.md
- fix version detection (WSL API returned unreliable results)
- improve instance IP address detection
- improve attach prerequisites checks
- silence bogus "already shared" info message
- improve documentation
Additional fixes:
- normalize table headers to CAPITALIZED (just like wsl.exe)
- all console reporting to stderr
- check server running
- fix double 'list' header
- fix 'unbind' registry access
> Improve WSL handling

- UsbIpServer/DeviceChangeWatcher.cs
- UsbIpServer/Program.cs
I was running into some weird issues where a `NullReferenceException` was sometimes thrown by [`SortedSet.Node.Rotate()`](https://source.dot.net/#System.Collections/System/Collections/Generic/SortedSet.cs,1766) when called by this line in `GetRemovedDevicesAsync()`.
```csharp
lastKnownBusIds?.ExceptWith(newBusIds);
```
I wasn't able to completely track down the root cause of the issue, but I did notice that `GetRemovedDevicesAsync()` was repeatedly called by different worker threads during debugging, so I suspect two threads were trying to access the `SortedSet` at the same time and corrupted the state of the internal tree. This PR adds a semaphore to lock access to the members of `DeviceChangeWatcher`
I also added a note to the error message when the WSL switch IP address can't be found, …
> Add lock for thread safety in DeviceChangeWatcher

- README.md
- UsbIpServer/AttachedClient.cs
- UsbIpServer/ConnectedClient.cs
- UsbIpServer/ExportedDevice.cs
- UsbIpServer/Interop/Linux.cs
- UsbIpServer/Interop/VBoxUsb.cs
- UsbIpServer/Lock.cs
- UsbIpServer/VBoxUsbMon.cs
As you can see, this is another bit of concurrency complexity.
Unfortunately, the new support also changes the code paths for the bulk endpoints. We need some thorough regression testing before I dare to merge this...
> Add support for intr/unlink and concurrent requests

- Installer/Product.wxs
- Support TARGETDIR, which is what winget uses
- As default, preserve install location on updates
> Allow overriding install location

- UsbIpServer/UsbConfigurationDescriptors.cs
Fix #54 
I am not sure if this is an accurate change. However, I believe it is better than the current situation where it crashes.
> ignore duplicated bConfigurationValue

- UnitTests/ParseBindCommand.cs
- UnitTests/ParseUnbindCommand.cs
- UnitTests/ParseWslAttachCommand.cs
- UnitTests/ParseWslDetachCommand.cs
- UsbIpServer/Program.cs
All releases use --busid, refactoring spelled it as --bus-id by mistake.
> Fix spelling of option --busid

- UsbIpServer/AttachedClient.cs
> Fix reply ordering per endpoint

- Directory.Packages.props
- UsbIpServer/UsbIpServer.csproj
Was a left-over from the .NET 5 to .NET 6 migration
> Remove obsolete Microsoft.Win32.Registry

- .editorconfig
- .github/workflows/build.yml
- Directory.Build.props
- Directory.Packages.props
- Installer/Installer.wixproj
- Installer/Product.wxs
- InstallerDependencies/InstallerDependencies.csproj
- NetStandard.props
- UnitTests/Automation_Tests.cs
- UnitTests/Parse_state_Tests.cs
- UnitTests/Program_Tests.cs
- UnitTests/UnitTests.csproj
- UsbIpServer/CommandHandlers.cs
- UsbIpServer/Program.cs
- UsbIpServer/UsbIpServer.csproj
- Usbipd.Automation/Device.cs
- Usbipd.Automation/IsExternalInit.cs
- Usbipd.Automation/State.cs
- Usbipd.Automation/Usbipd.Automation.csproj
- Usbipd.PowerShell/GetUsbipdDevice.cs
- Usbipd.PowerShell/GlobalSuppressions.cs
- Usbipd.PowerShell/Installation.cs
- Usbipd.PowerShell/Usbipd.PowerShell.csproj
- usbipd-win.sln
This PR adds helpers for scripted automation:
1. There is a new command `usbipd state`, which returns JSON for all USB devices. More easily parsed by scripts than the standard `list` output, with more information and without truncating long strings.
2. There is a PowerShell module that exposes a `Get-UsbipdDevice` cmdlet that uses the JSON from (1) and returns it as PowerShell objects, with even more (meta-)information like `IsConnected`, `IsAttached`, etc.
The PowerShell cmdlet is built on top of PowerShellStandard, so it can be used by standard Windows 10 PowerShell 5.1 (either x64 or x86) as well as PowerShell 7 from the store. For now, I do not intend to publish the PowerShell module to PowerShell Gallery, as the version is tightly coupled to the version of usbipd-win. You will have …
> Add PowerShell cmdlets

- Directory.Packages.props
- Usbipd/Usbipd.csproj
- Usbipd/WslDistributions.cs
The new version win10 win11 22H2 supports wsl2 bridged mode.
Reference link https://github.com/microsoft/WSL/issues/4150 .
It changes the name of vmSwitch from the default "WSL" to a user-modifiable one.
Set in the SpecialFolder.UserProfile/.wslconfig file as follows:
[wsl2]
networkingMode=bridged
vmSwitch=usermodifiable
> support wsl2 bridged mode

- Usbipd/AttachedClient.cs
This PR addresses BSOD issue while using ADB, but also other with tools as reported in https://github.com/dorssel/usbipd-win/issues/248#issuecomment-1506862740
The code change is small but diagnosing the issue was a substantial effort.
Here is the analysis:
0. Setup
Hyper-V VM with Debian 11 (unstable) guest
Host: Windows 10 (Version 10.0.19045 Build 19045)
ADB for Android Nougat
Custom ADB device
1. ADB
ADB tool that I’ve used to reproduce the issue was an older version e.g. from Android Nougat
In this version of the tool data is sent in chunks of size 256k.
Dimitar Stankov provided me with custom build of this ADB version with reduced chunk size of 16k, 
because I’ve suspected that chunk size goes beyond VboxUSB limits. Chunk size turned out not to be the case eventually.
Dimitar …
> bugfix: Handle zero-len packets from ADB to avoid BSOD

- Usbipd/wsl-scripts/auto-attach.sh
When running this as a systemd service, I don't have permissions to access `/proc/self/fd/1`. However, during my trial and errors, you don't need this, but read will by default wait for stdin if called without a pipe.
> Fix auto-attach when running as a systemd service

- UnitTests/Parse_attach_Tests.cs
- UnitTests/Parse_wsl_Tests.cs
- Usbipd/AttachedEndpoint.cs
- Usbipd/CommandHandlers.cs
- Usbipd/Program.cs
- Usbipd/VBoxUsbMon.cs
- move 'wsl attach' to 'attach --wsl'
- mark 'wsl' as obsolete
- remove "bind if required and admin" from attach
> Move attach command to top level

- Usbipd/Wsl.cs
- remove `--shell-type none` as it is redundant when using `--exec`
Fixes https://github.com/dorssel/usbipd-win/issues/861
> Fix support for older WSL versions

- Directory.Packages.props
- UsbIds/UsbIds.csproj
- remove unnecessary explicit Microsoft.CodeAnalysis.Analyzers reference
> Bump Microsoft.CodeAnalysis.CSharp from 4.8.0 to 4.9.2

- .github/linters/.markdownlint.json
- .github/linters/.prettierrc.json
- global.json
These are automatically picked up from JSON Schema Store (and don't define $schema itself as an allowed property).
> Fix JSON schemas

- Directory.Build.props
- Directory.Build.targets
- UnitTests/packages.lock.json
- Usbipd.Automation/packages.lock.json
- Usbipd/Properties/PublishProfiles/InputForInstaller_win-arm64.pubxml
- Usbipd/Properties/PublishProfiles/InputForInstaller_win-x64.pubxml
- Usbipd/packages.lock.json
- Dependabot cannot handle composite TargetFramework
- also improves netstandard packages.lock
> Fix Dependabot

- Directory.Build.props
- SDK reverted this to 'direct', but we really want 'all'
- also set other option to strict, even though this is the (current) default
> Force NuGetAudit for transitive packages
